const quizList = [
  {
    who: "hyeon",
    quiz: "1 + 1은?",
    mission: "장수탕 선녀님을 읽고 다음 문제를 푸세요",
    answer: "2",
    isCorrect: false,
  },
  {
    who: "hyeon",
    quiz: "장수탕 선녀님이 좋아하는 것은?",
    mission: "",
    answer: "요구르트",
    isCorrect: false,
  },
  {
    who: "hyeon",
    quiz: "7는 ㅁ보다 1 크다.",
    mission: "",
    answer: "6",
    isCorrect: false,
  },
  {
    who: "hyeon",
    quiz: "축하합니다. 문제를 모두 풀었습니다.",
    mission: "",
    answer: "",
    isCorrect: false,
  },
  {
    who: "hun",
    quiz: "빵을 영어로 쓰시오",
    mission: "",
    answer: "bread",
    isCorrect: false,
  },
  {
    who: "hun",
    quiz: "학생을 영어로 쓰시오",
    mission: "이상한 손님을 읽고 다음 문제를 푸세요",
    answer: "student",
    isCorrect: false,
  },
  {
    who: "hun",
    quiz: "이상한 손님의 이름은?",
    mission: "",
    answer: "천달록",
    isCorrect: false,
  },
  {
    who: "hun",
    quiz: "학생을 영어로 쓰시오",
    mission: "",
    answer: "student",
    isCorrect: false,
  },
  {
    who: "hun",
    quiz: "축하합니다. 문제를 모두 풀었습니다.",
    mission: "",
    answer: "",
    isCorrect: false,
  },
];
